In [63]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score
import copy
import numpy as np
from sklearn.neighbors import KNeighborsClassifier

In [64]:

df = pd.read_csv(r"D:\Sem 4\ML LABS\DataSets\iris.csv")
y = df.pop("species")
X = df
knn = KNeighborsClassifier(n_neighbors=5)
xtrain,xtest,ytrain,ytest = train_test_split(X,y,train_size=0.8,random_state=42)
knn.fit(xtrain,ytrain)
ypred = knn.predict(xtest)
# display(xtest)
print(f"Confusion Matrix :\n {confusion_matrix(ypred,ytest)}")
# print(pd.Series(data['target']).unique())


Confusion Matrix :
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [70]:
import pandas as pd

def chi_squared(x, y):
    return (x - y) ** 2 / (x + y) if (x + y) != 0 else 0  

def Assign_label(data, sums, k):
    temp = data.copy(deep=True)
    temp["sums"] = sums
    temp = temp.sort_values(by="sums", ascending=True)

    labels = pd.Series(data['species']).unique()
    max_labels = {}
    for i in range(len(labels)):
        max_labels[labels[i]] = 0

    for i in range(k):
        sp = temp.iloc[i]['species']   
        max_labels[sp] += 1

    return max(max_labels, key=max_labels.get)

def Predict(xtrain, ytrain, xt, k):
    data = pd.concat([xtrain, ytrain], axis=1)
    y = []
    cols = xt.columns


    for j in range(xt.shape[0]):  
        sums = []
        for i in range(data.shape[0]):  
            sumcols = 0
            for col in cols:
                sumcols += chi_squared(data.iloc[i][col], xt.iloc[j][col])
            sums.append(sumcols)

        labeled = Assign_label(data, sums, k)
        y.append(labeled)   

    return y


In [72]:
Y = Predict(xtrain,ytrain,xtest,5)
print(f"Accuracy Score :\n {confusion_matrix(Y,ypred)}")

Accuracy Score :
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
